// This is just an example for the custom fields you have on your deals collection; in my case, as I showed in the video, for the marketplaces of my company
// you will need to adapt it to your own case, for more info about it, check my video con youtube
let
    Origen = Json.Document(Web.Contents("https://yourcompany.pipedrive.com/v1/dealFields?api_token=y0uRc0mp4nyt9k3n")),
    #"Convertida en tabla" = Table.FromRecords({Origen}),
    #"Se expandió data" = Table.ExpandListColumn(#"Convertida en tabla", "data"),
    #"Se expandió data1" = Table.ExpandRecordColumn(#"Se expandió data", "data", {"id", "key", "name", "order_nr", "picklist_data", "field_type", "is_subfield", "json_column_flag", "add_time", "update_time", "last_updated_by_user_id", "active_flag", "edit_flag", "index_visible_flag", "details_visible_flag", "add_visible_flag", "important_flag", "bulk_edit_allowed", "searchable_flag", "filtering_allowed", "sortable_flag", "use_field", "link", "options", "mandatory_flag", "bulk_edit_allowed_conditions"}, {"data.id", "data.key", "data.name", "data.order_nr", "data.picklist_data", "data.field_type", "data.is_subfield", "data.json_column_flag", "data.add_time", "data.update_time", "data.last_updated_by_user_id", "data.active_flag", "data.edit_flag", "data.index_visible_flag", "data.details_visible_flag", "data.add_visible_flag", "data.important_flag", "data.bulk_edit_allowed", "data.searchable_flag", "data.filtering_allowed", "data.sortable_flag", "data.use_field", "data.link", "data.options", "data.mandatory_flag", "data.bulk_edit_allowed_conditions"}),
    #"Se expandió data.bulk_edit_allowed_conditions" = Table.ExpandRecordColumn(#"Se expandió data1", "data.bulk_edit_allowed_conditions", {"status"}, {"data.bulk_edit_allowed_conditions.status"}),
    #"Se expandió additional_data" = Table.ExpandRecordColumn(#"Se expandió data.bulk_edit_allowed_conditions", "additional_data", {"pagination"}, {"additional_data.pagination"}),
    #"Se expandió additional_data.pagination" = Table.ExpandRecordColumn(#"Se expandió additional_data", "additional_data.pagination", {"start", "limit", "more_items_in_collection"}, {"additional_data.pagination.start", "additional_data.pagination.limit", "additional_data.pagination.more_items_in_collection"}),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Se expandió additional_data.pagination",{{"success", type logical}, {"data.id", Int64.Type}, {"data.key", type text}, {"data.name", type text}, {"data.order_nr", Int64.Type}, {"data.picklist_data", type any}, {"data.field_type", type text}, {"data.is_subfield", type logical}, {"data.json_column_flag", type logical}, {"data.add_time", type datetime}, {"data.update_time", type datetime}, {"data.last_updated_by_user_id", Int64.Type}, {"data.active_flag", type logical}, {"data.edit_flag", type logical}, {"data.index_visible_flag", type logical}, {"data.details_visible_flag", type logical}, {"data.add_visible_flag", type logical}, {"data.important_flag", type logical}, {"data.bulk_edit_allowed", type logical}, {"data.searchable_flag", type logical}, {"data.filtering_allowed", type logical}, {"data.sortable_flag", type logical}, {"data.use_field", type text}, {"data.link", type text}, {"data.options", type any}, {"data.mandatory_flag", type any}, {"data.bulk_edit_allowed_conditions.status", type text}, {"additional_data.pagination.start", Int64.Type}, {"additional_data.pagination.limit", Int64.Type}, {"additional_data.pagination.more_items_in_collection", type logical}}),
    #"Se expandió data.options" = Table.ExpandListColumn(#"Tipo cambiado", "data.options"),
    #"Se expandió data.options1" = Table.ExpandRecordColumn(#"Se expandió data.options", "data.options", {"color", "label", "id"}, {"data.options.color", "data.options.label", "data.options.id"}),
    #"Filas filtradas" = Table.SelectRows(#"Se expandió data.options1", each ([data.name] = "Marketplace")),
    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Filas filtradas",{{"data.options.id", "Marketplace_id"}})
in
    #"Columnas con nombre cambiado"
